version: 1
disable_existing_loggers: False

formatters:
  default:
    (): "uvicorn.logging.DefaultFormatter"
    fmt: "%(levelprefix)s %(asctime)s - %(name)s - [%(levelname)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    use_colors: True
  access:
    (): "uvicorn.logging.AccessFormatter"
    fmt: '%(levelprefix)s %(asctime)s - %(client_addr)s - "%(request_line)s" %(status_code)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
    use_colors: True

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout

loggers:
  # Наш код приложения
  src.main:
    handlers: [default]
    level: INFO
    propagate: no
  src.model_manager:
    handlers: [default]
    level: INFO
    propagate: no
  
  # Логи Uvicorn
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: no