# docker-compose.yml
version: '3.8'

services:
  # Сервис вашего API
  api:
    build: .
    container_name: kb_api
    ports:
      - "8001:8001"
    env_file:
      - .env.docker
    # Мы убрали 'depends_on', так как больше не управляем базой данных и S3
    restart: unless-stopped